// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZh9y79argmZ1SC2vL298UPG115RaJAM',
    appId: '1:273380838834:web:cd5e372ab17f90044568ab',
    messagingSenderId: '273380838834',
    projectId: 'starter-49da2',
    authDomain: 'starter-49da2.firebaseapp.com',
    storageBucket: 'starter-49da2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDHMuDXBtM3K9Tq70V9wtV-R7Ihr03mI',
    appId: '1:273380838834:android:41b3e61f3a5ed9b04568ab',
    messagingSenderId: '273380838834',
    projectId: 'starter-49da2',
    storageBucket: 'starter-49da2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGXXFX4RTZAXxqzS-KfU2Y_-pwwzVa04',
    appId: '1:273380838834:ios:03b006d1a21ea54d4568ab',
    messagingSenderId: '273380838834',
    projectId: 'starter-49da2',
    storageBucket: 'starter-49da2.appspot.com',
    iosClientId: '273380838834-h24kgnug4pd5kbicl650dl54jm7gjluk.apps.googleusercontent.com',
    iosBundleId: 'com.example.starter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjGXXFX4RTZAXxqzS-KfU2Y_-pwwzVa04',
    appId: '1:273380838834:ios:03b006d1a21ea54d4568ab',
    messagingSenderId: '273380838834',
    projectId: 'starter-49da2',
    storageBucket: 'starter-49da2.appspot.com',
    iosClientId: '273380838834-h24kgnug4pd5kbicl650dl54jm7gjluk.apps.googleusercontent.com',
    iosBundleId: 'com.example.starter',
  );
}
